version: '3'

services:

  server:
    container_name: rust-web-server
    hostname: rust-web-server
    restart: always
    ports:
      - "3333:7878"
    build: ./server
    # networks:
    #   - rust-web

  client:
    container_name: rust-web-client
    hostname: rust-web-client
    restart: always
    build: ./client
    depends_on:
      - server
    # networks:
    #   - rust-web

# networks:
#   rust-web:
#     external: true
